# Generated by Django 6.0.3 on 2026-03-22 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TBL_Usuario',
            fields=[
                ('id_nomina', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Número de nómina')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del usuario')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'TBL_Usuario',
            },
        ),
        migrations.CreateModel(
            name='TBL_Video',
            fields=[
                ('id_video', models.AutoField(primary_key=True, serialize=False, verbose_name='ID del video')),
                ('titulo', models.CharField(max_length=50, verbose_name='Título del video')),
                ('nombre_video', models.CharField(max_length=50, verbose_name='Nombre del video')),
                ('extension', models.CharField(max_length=5, verbose_name='Extensión del video')),
                ('tamano', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Tamaño (MB)')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'db_table': 'TBL_Video',
            },
        ),
        migrations.CreateModel(
            name='TBL_UsuarioVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.tbl_usuario', verbose_name='Usuario')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.tbl_video', verbose_name='Video')),
            ],
            options={
                'verbose_name': 'Relación Usuario-Video',
                'verbose_name_plural': 'Relaciones Usuario-Video',
                'db_table': 'TBL_UsuarioVideo',
            },
        ),
    ]
